server:
  port: 8080
twitter-to-kafka-service:
    twitter-keywords:
      - Java
      - Microservices
      - Spring
      - Kafka
      - ElasticSearch
    welcome-message: Welcome to Microservices with Kafka and Twitter!
    enable-mock-tweets: true
    mock-min-tweet-lenght: 5
    mock-max-tweet-lenght: 15
    mock-sleep-ms: 10000
retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  max-attempts: 3
  sleep-time-ms: 2000
